### PR TITLE
Environment using Helm chart

### PR DESCRIPTION
**Pull request by giubacc**
Please note that this PR depends on https://github.com/aquarist-labs/s3gw-charts/pull/8
 
- Added s3gw-charts submodule
- Modified environment playbooks to use the chart
- Removed manifest yamls and scripts relying on old stuff
- Fixed documentation

Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>

### CODE REVIEW

**Comment by jecluis** [comment]
Does this mean we will only be able to deploy using the helm chart, and not by installing the yaml file?

**Comment by giubacc** [comment]
> Does this mean we will only be able to deploy using the helm chart, and not by installing the yaml file?

Yes, the aim of this PR is to support only helm as installation option.
Because we are maintaining an helm chart repository, that should be the unique manifest source.
Having yamls duplicated here could be not desirable and lead to confusion.
This is my opinion btw, we can discuss this.

**Comment by jecluis** [comment]
I'm not sure whether we should remove the yaml files altogether. I like the idea of having a setup script that sets up a minimal system to be played with, without the need to go through having to do stuff manually before installing the s3gw via the helm chart.

Other's thoughts would be interesting on this one. @0xavi0 @votdev @l-mb @jhmarina ?

**Comment by giubacc** [comment]
> I'm not sure whether we should remove the yaml files altogether. I like the idea of having a setup script that sets up a minimal system to be played with, without the need to go through having to do stuff manually before installing the s3gw via the helm chart.
> 
> Other's thoughts would be interesting on this one. @0xavi0 @votdev @l-mb @jhmarina ?

Just a clarification: installation process is completely automated when building a vm based cluster, because that is an ephemeral environment that the user can destroy at will when she wants.
For bare metal installation this is not, but that is intended; main motivation is that if were doing so we would have to take the responsibility to provide a way to uninstall all the stuff from the machine of the user.
Give the user a generic indication to use an helm chart implies that helm is the main tool he has to use to install/uninstall s3gw.

**Comment by jhmarina** [comment]
I'd imagine that it is always best to avoid duplicity. If the chart provides the same minimal system that the `yaml` files do, perhaps it makes sense to get rid of them. 

It would be interesting to know what other devs think.

**Comment by giubacc** [comment]
This has been too much opened, now there are conflicts, so it must be patched.
I'm closing this, we will eventually evaluate in the future if this is something worth to do.

**Pull request closed without merging**
